import {
  AuthAppsGetUrlByUser,
  AuthAppsLogin,
  ComplainCategory,
  ComplainLandingPasignationApps,
  CreateAssetHealthCheckedTransaction,
  CreateComplain,
  CreateExpenceRegisterApps,
  CreateNPTEntry,
  DeleteExpenseById,
  DeleteNPTById,
  DeleteOeeProductionId,
  EditAssetHealthCheckedTransaction,
  EditExpenseRegister,
  EditExpenseRegisterForApps,
  GRNFileUpload,
  GetBoMNameDDL,
  GetCostCenterDDL,
  GetCostElementByCostCenter,
  GetCustomerStatementOnCrLimitForSales,
  GetDistributionChannelDDL,
  GetExpenseById,
  GetExpenseLandingPaginationApps,
  GetHealthCheckedTransactionById,
  GetHealthCheckedTransactionPagination,
  GetItemSalesByChanneldDDL,
  GetNPTById,
  GetNPTLanding,
  GetNPTLossTime,
  GetNPTSubCategoryById,
  GetNptCapacityconfigByItemAndBomId,
  GetOeeProductWastById,
  GetOeeProductWastLanding,
  GetWastedItemDDL,
  GetPartnerBook,
  GetPlantNameDDL,
  GetProductionShiftDDL,
  GetProfitcenterDDLByCostCenterId,
  CreateStuffBusBooking,
  GetStuffBusBookingLanding,
  GetStuffBusBookingById,
  GetDriverBasicInfoById,
  DeleteStuffBusBookingById,
  GetShopfloorDDL,
  GetTodayHealthCheck,
  GetTodayHealthCheckById,
  GetTodayHealthCheckTranById,
  GetUrlByUserGmailId,
  GetVehicleList,
  GetVehicleLogLanding,
  GetWorkCenterDDL,
  MSILAllDDLByPartName,
  OeeProductionWasteEntry,
  ShopFloorDDL,
  UploadFile,
  UploadFileUnlimited,
  WorkMachineDDL,
  GetApproveListBySuppervisorId,
  TripRequisitionApprove,
  GetStuffBusBookingLandingWithFilter,
  GetBookingListForApprovalByEnroll,
  GetAvailableDriverList,
  GetLastVehicleMileageId,
  GetItemNameForNPTDDL,
  CreateVehicleLog,
  CreateVehicleCheckPointLog,
  GetVehicleLogById,
  GetSupplierFuelStationDDL,
  CreateVehicleExpenseLog,
  GetDriverDetailsByEnroll,
  GetChallanStatusAnalysisReport,
  CalculateAmountToLiter,
  GetMarketShareSalesContributionPagination,
  GetMarketShareCompanyDDL,
  CreateMarketShareSalesContribution,
  GetMarketShareSalesContributionByTerritoryId,
  EditMarketShareSalesContribution,
  GetSupplierListWithRanks,
  GetUserWiseRegionAreaTerritoryDDL,
  GetTripApprovalLanding,
  UpdateVehicleExpenseLog,
  GetVehicleListByDriverId,
  GetMarketShareByTerritoryNDate,
  GetMasterSectionDDL,
  train,
  check_attendance,
  MassonBillEntry,
  GetMassonBill,
  GetEmployeeLoginInfoForSales,
  GetVehicleFuelTypeDDL,
  VehicleDDl,
  CreateUpdateFuelRequsition,
  FuelRequsitionLanding,
  UploadFuelRequsitionAttatchment,
  GetFuelRequsitionById,
  GetSupplierFuelStationDDLForFuelDelivery,
  UploadFuelRequsitionQRScan,
  SendContact,
  GetDeliveryToAssignSupplierPagination,
  GetBusinessAreaDDL,
  GetDistributionChannelDDLBySBUId,
  GetShipPointDDL,
  GetTerritoryBySupplierId,
  AssignSupplierToDelivery,
  GetVehicleCityDDL,
  GetVehicleRegistrationLetterDDL,
  GetVehicleRegitrationNumberDDL,
  GetVehicleCapacityDDL,
  CreateSupplierVehicleApps,
  GetVehicleBySupplierDDL,
  GetDivisionDDL,
  GetDistrictDDL,
  GetThanaDDL,
  CustomerRegistrationLogin,
  LoginForPartnerRegistration,
  GetBusinessUnitDDL,
  CreateEmployeeVisitingCardData,
  GetBUPurchaseOrganizationDDL,
  GetOrganizationalUnitUserPermissionPR,
  GetOrganizationalUnitUserPermissionforWearhouse,
  GetIndentStatement,
  GetStandardItemTypeListDDL,
  GetItemCategoryDDLByTypeId,
  GetItemPlantWarehouseForPurchaseRequestSearchDDL,
  VehicleAssignAsDriver,
  GetControllingUnit,
  GetCostCenter,
  GetProfitCenter,
  GetCostElementByCostCenterProcurement,
  getSupplierConfigBySupplierId,
  IsPossiblePOAutoApproval,
  GetFuelRequsitionReportDayWise,
  GetFuelRequsitionReportCarWise,
  GetSupplierConfigLandingforAutoPO,
  SupplierPasswordReset,
  GetDeliveryPrintInfo,
  CompletePacker,
  CreateVehicleForG2G,
  ConfirmVehicleBySupplierApps,
  GetVehicleInfoByOwnerTypeDDL,
  GetAssignedVehicleSupplierInfoApps,
  GetDeliveryPrintInfoByVehicleCardNumber,
  GETBankDDl,
  GETBankBranchDDl,
  UpdateIHBUserApproval,
  SendOtpToRecoverPassword,
  VerifyOtpToRecoverPassword,
  RecoverPassword,
  GetAvailableStaffVehicleReport,
  GetProjectStatusDDL,
  GetTransportZoneByDistrictDDL,
  GetEmployeeDDLSearchByBU,
  GetUserWiseShipToPartnerAndZoneDDL,
  GetReferraSourceDDL,
  CreateCustomerAcquisition,
  GetItemSalesByItemTypeIdDDL,
  GetCustomerAcquisitionPagination,
  UpdateCustomerAcquisitionPipeline,
  GetBugetHeadWiseBalance,
  GetAvailableBudgetAdvanceBalance,
  GetFollowUpActivityTypeDDL,
  CreateCustomerFollowUpActivity,
  GetCustomerFollowUpActivity,
  GetGetFuelCostPerKM,
  CreateLinkedInPost,
  GetLinkedInPosts,
  GetPartnerBenefitPolicyByDetails,
  GetPartnerBenefitData,
  GetBusinessPartnerSearchDDL,
  CreatePartnerBenefitPolicy,
  GetBusinessPartnerShipPoint,
  GetPartnerBenefitPolicyLanding,
  GetTerrotoryRegionAreaByChannel,
  GetlSalesOfficerDDL,
  GetLabelNValueForDDL,
  GetShipPointByTerritoryID,
  GetPartnerBenefitPendingApproval,
  ComparativeStatementAutoPO,
  GetPurchaseOrderInformationPDF,
  CreateAdvanceExpense,
  GetAdvanceExpenseLandingPasignation,
  GetSBUListDDL,
  GetItemRateFromRateUpdateConfiguration,
  GetRateFromItemRateAgreement,
  GetAllContractorRegistration,
  GetSiteInfoPagination,
  GetSiteInfoById,
  SiteApproval,
  UserApproval,
  EditSiteInfo,
  AdvanceExpenseLandingForApps,
  GetAdvanceExpenseById,
  EditAdvanceExpense,
  GetAssetHealthCheckedTransactionForMaintenacne,
  GetDamageAssetHealthCheckedTransactionById,
  CreateHealthCheckedDamageAssetMaintenance,
  GetItems,
  GetEmployeeInfo,
  GetNearByPartner,
  GetInstrumentTypeDDL,
  CreateAllMachineBulkHeathCheck,
  GetInventoryStatement,
  SaveAuditLog,
  VerifyOTP,
  GetCostElementByCostCenterForExpense,
  MillRulesApproval,
  GetMillRuleWithHeaderAsync,
  CoomonApprovalList,
  GetItemRequestViewById,
  CommonApproved,
  BOMApprovalLanding,
  BOMApproval,
  GetPONOLcNoforLCSummeryDDL,
  GetInfoFromPoLcDDLApprove,
  ImportCostSheetReport,
  GetShipmentById,
  ApproveCommercialCoating,
  GetLoanItemLanding,
  ItemInventoryLoanTransaction,
  GetBusinessPartnerbyIdDDL,
  GetBusinessUnitByAccountDDL,
  GetFundTransferApprovaListForCreatePagination,
  CreateOrEditFundTransferRequest,
  GetPendingAdjustments,
  GetAllVisitorRequest,
  AcceptOrRejectVisitorRequest,
  CreateVisitorAppointment,
  GetAllMyOutgoingRequest,
  GetPendingAdjustmentRowViewByTransId,
  AdjustmentApproval,
  PartnerRegistrationApproval,
  GetVehicleNearbyLocation,
  ShippingLocationTracking,
  get_meeting_room_calender,
  GetValidateExpenseAttachment,
  DeleteExpenseRegisterRow,
  create_meeting_event,
  get_meeting_room_calender_modified,
  list_user_task_modified,
  create_user_task,
  GetItemMasterCategoryDDL,
  GetItemMasterSubCategoryDDL,
  LighterVesselLocationTracking,
  truck_api,
  truck_api_token,
  GetServiceItemListByWhId,
  GetAssetListForWorkOrder,
  CreateWorkOrder,
  GetCostCenterList,
  GetMntWorkOrderList,
  GetMaintenanceWorkOrder,
  GetMaintenceTaskRowData,
  EditWorkOrder,
  CreateMntTask,
  GetMaintenaceTaskItemList,
  GetPartsList,
  GetRuningStockAndQuantityList,
  CreateMntItemTask,
  CancelMntItemTask,
  CreateItemRequestForAssetMaintenance,
  GetProjectDDL,
  GetEmployeeRegisterSummaryAllUnit,
  GetFuelCostByEmployee,
  GetCustomerAssessmentDocumentType,
  CreateCustomerPreAssesment,
  GetBillUpdateFuelCostByEmployee,
  GetCustomerPreAssessmentLanding,
  GetCustomerPreAssessmentValueByType,
  GetCustomerPreAssessmentApprovalInfo,
  CreateCustomerPreAssessmentApproval,
  GetMaintenanceBreakdown,
  CreateSalesForceAssessment,
  GetSalesForceEmployeeDDL,
  GetSalesForcePreAssessmentLanding,
  GetSalesForceAssessmentApprovalInfo,
  CreateSalesForceAssessmentApproval,
  list_user_task,
  CreateVoiceRecord,
  GetVoiceRecord,
  CreateSupplierAdvanceAfterPoApproved,
  AppLoginLinkedin,
  chat,
  GetDemandPlan,
  SaveOrUpdateManpowerTaskPerform,
  GetEmployeeWiseProfitCenterConfig,
  GetCostElementByTransportDDL,
  DomainDownloadFile,
} from './api';

const withoutEncryptionApi = [
  '/Document/DownloadFile',
  'signal.peopledesk.io/NotificationHub',
  '/Document/UploadFile',
  '/Document/UploadProfilePicture',
  '/PdfAndExcelReport/EmployeePaySlipReport',
  // Returns raw HTML (Type=htmlView), so it must bypass decryption.
  '/PdfAndExcelReport/EmployeeSalaryPayslip',
  '/PdfAndExcelReport/BankAdviceReportForIBBL',
  '/document/downloadfile',
  'emp/Document/UploadFileBaseSixtyFour',
  '/crm/Lead/CRMLeadLandingForPeopledesk',
  '/crm/Lead/CRMLeadAccountSaveForPeopledesk',
  '/EProcurement/DownlloadFile',
  '/reverse.php',
  // new add for v2
  // '/AuthApps/Login',
  // '/Auth/GetMenuListPermissionWiseApps',
  // '/ApprovalPipeline/RemoteAttendanceLocationNDeviceApproval',
  // '/ApprovalPipeline/RemoteAttendanceApproval',

  // '/PushNotify/PushNotifyDeviceRegistration',
  GetUrlByUserGmailId,
  AuthAppsLogin,
  AuthAppsGetUrlByUser,
  GRNFileUpload,
  // GetPartnerBook,
  // GetCustomerStatementOnCrLimitForSales,
  // GetItemSalesByChanneldDDL,
  // GetDistributionChannelDDL,
  // ComplainCategory,
  // CreateComplain,
  // ComplainLandingPasignationApps,
  // GetExpenseById,
  // CreateExpenceRegisterApps,
  // GetExpenseLandingPaginationApps,
  // GetProfitcenterDDLByCostCenterId,
  // GetCostElementByCostCenter,
  // GetCostCenterDDL,
  // DeleteExpenseById,
  // GetTodayHealthCheckById,
  // CreateAssetHealthCheckedTransaction,
  // GetTodayHealthCheck,
  // WorkMachineDDL,
  // ShopFloorDDL,
  // GetHealthCheckedTransactionPagination,
  // GetHealthCheckedTransactionById,
  UploadFile,
  // Multipart, so it cannot be encrypted — the rest of ApkApp is.
  UploadFileUnlimited,
  DomainDownloadFile,
  // GetTodayHealthCheckTranById,
  // EditAssetHealthCheckedTransaction,
  // GetPlantNameDDL,
  // GetShopfloorDDL,
  // GetWorkCenterDDL,
  // GetBoMNameDDL,
  // GetProductionShiftDDL,
  // GetWastedItemDDL,
  // OeeProductionWasteEntry,
  // GetOeeProductWastLanding,
  // GetVehicleLogLanding,
  // GetOeeProductWastById,
  // GetNptCapacityconfigByItemAndBomId,
  // GetNPTLossTime,
  // MSILAllDDLByPartName,
  // GetNPTSubCategoryById,
  // CreateNPTEntry,
  // GetNPTById,
  // DeleteNPTById,
  // GetNPTLanding,
  // EditExpenseRegister,
  // EditExpenseRegisterForApps,
  // DeleteOeeProductionId,
  // GetVehicleList,
  // CreateStuffBusBooking,
  // GetStuffBusBookingLanding,
  // GetStuffBusBookingById,
  // GetDriverBasicInfoById,
  // DeleteStuffBusBookingById,
  // GetApproveListBySuppervisorId,
  // TripRequisitionApprove,
  // GetStuffBusBookingLandingWithFilter,
  // GetBookingListForApprovalByEnroll,
  // GetAvailableDriverList,
  // GetLastVehicleMileageId,
  // GetItemNameForNPTDDL,
  // CreateVehicleLog,
  // CreateVehicleCheckPointLog,
  // GetVehicleLogById,
  // GetSupplierFuelStationDDL,
  // CreateVehicleExpenseLog,
  // GetDriverDetailsByEnroll,
  // GetChallanStatusAnalysisReport,
  // CalculateAmountToLiter,
  // GetMarketShareSalesContributionPagination,
  // GetMarketShareCompanyDDL,
  // CreateMarketShareSalesContribution,
  // GetMarketShareSalesContributionByTerritoryId,
  // EditMarketShareSalesContribution,
  // GetSupplierListWithRanks,
  // GetUserWiseRegionAreaTerritoryDDL,
  // GetTripApprovalLanding,
  // UpdateVehicleExpenseLog,
  // GetVehicleListByDriverId,
  // GetMarketShareByTerritoryNDate,
  // GetMasterSectionDDL,
  train,
  check_attendance,
  // MassonBillEntry,
  // GetMassonBill,
  // GetEmployeeLoginInfoForSales,
  // GetVehicleFuelTypeDDL,
  // VehicleDDl,
  // CreateUpdateFuelRequsition,
  // FuelRequsitionLanding,
  // UploadFuelRequsitionAttatchment,
  // GetFuelRequsitionById,
  // GetSupplierFuelStationDDLForFuelDelivery,
  // UploadFuelRequsitionQRScan,
  SendContact,
  // GetDeliveryToAssignSupplierPagination,
  // GetBusinessAreaDDL,
  // GetDistributionChannelDDLBySBUId,
  // GetShipPointDDL,
  // GetTerritoryBySupplierId,
  // AssignSupplierToDelivery,
  // GetVehicleCityDDL,
  // GetVehicleRegistrationLetterDDL,
  // GetVehicleRegitrationNumberDDL,
  // GetVehicleCapacityDDL,
  // CreateSupplierVehicleApps,
  // GetVehicleBySupplierDDL,
  // GetDivisionDDL,
  // GetDistrictDDL,
  // GetThanaDDL,
  // CustomerRegistrationLogin,
  // LoginForPartnerRegistration,
  // GetBusinessUnitDDL,
  // CreateEmployeeVisitingCardData,
  // GetBUPurchaseOrganizationDDL,
  // GetOrganizationalUnitUserPermissionPR,
  // GetOrganizationalUnitUserPermissionforWearhouse,
  // GetIndentStatement,
  // GetStandardItemTypeListDDL,
  // GetItemCategoryDDLByTypeId,
  // GetItemPlantWarehouseForPurchaseRequestSearchDDL,
  // VehicleAssignAsDriver,
  // GetControllingUnit,
  // GetCostCenter,
  // GetProfitCenter,
  // GetCostElementByCostCenterProcurement,
  // getSupplierConfigBySupplierId,
  // IsPossiblePOAutoApproval,
  // GetFuelRequsitionReportDayWise,
  // GetFuelRequsitionReportCarWise,
  // GetSupplierConfigLandingforAutoPO,
  // SupplierPasswordReset,
  // GetDeliveryPrintInfo,
  // CompletePacker,
  // CreateVehicleForG2G,
  // ConfirmVehicleBySupplierApps,
  // GetVehicleInfoByOwnerTypeDDL,
  // GetAssignedVehicleSupplierInfoApps,
  // GetDeliveryPrintInfoByVehicleCardNumber,
  // GETBankDDl,
  // GETBankBranchDDl,
  // UpdateIHBUserApproval,
  SendOtpToRecoverPassword,
  VerifyOtpToRecoverPassword,
  RecoverPassword,
  // GetAvailableStaffVehicleReport,
  // GetProjectStatusDDL,
  // GetTransportZoneByDistrictDDL,
  // GetEmployeeDDLSearchByBU,
  // GetUserWiseShipToPartnerAndZoneDDL,
  // GetReferraSourceDDL,
  // CreateCustomerAcquisition,
  // GetItemSalesByItemTypeIdDDL,
  // GetCustomerAcquisitionPagination,
  // UpdateCustomerAcquisitionPipeline,
  // GetBugetHeadWiseBalance,
  // GetAvailableBudgetAdvanceBalance,
  // GetFollowUpActivityTypeDDL,
  // CreateCustomerFollowUpActivity,
  // GetCustomerFollowUpActivity,
  // GetGetFuelCostPerKM,
  // CreateLinkedInPost,
  // GetLinkedInPosts,
  // GetPartnerBenefitPolicyDDL,
  // GetPartnerBenefitData,
  // GetBusinessPartnerSearchDDL,
  // CreatePartnerBenefitPolicy,
  // GetBusinessPartnerShipPoint,
  // GetPartnerBenefitPolicyLanding,
  // GetTerrotoryRegionAreaByChannel,
  // GetlSalesOfficerDDL,
  // GetPartnerBenefitPolicyByDetails,
  // GetLabelNValueForDDL,
  // GetShipPointByTerritoryID,
  // GetPartnerBenefitPendingApproval,
  // ComparativeStatementAutoPO,
  // GetPurchaseOrderInformationPDF,
  // CreateAdvanceExpense,
  // GetAdvanceExpenseLandingPasignation,
  // GetSBUListDDL,
  // GetItemRateFromRateUpdateConfiguration,
  // GetRateFromItemRateAgreement,
  'extension_status.php',
  // GetAllContractorRegistration,
  // GetSiteInfoPagination,
  // GetSiteInfoById,
  // SiteApproval,
  // UserApproval,
  '/proxy/network/api/s/default/cmd/hotspot',
  '/proxy/network/api/s/default/stat/voucher',
  // EditSiteInfo,
  // AdvanceExpenseLandingForApps,
  // GetAdvanceExpenseById,
  // EditAdvanceExpense,
  // GetAssetHealthCheckedTransactionForMaintenacne,
  // GetDamageAssetHealthCheckedTransactionById,
  // CreateHealthCheckedDamageAssetMaintenance,
  // GetItems,
  // GetEmployeeInfo,
  // GetNearByPartner,
  // GetInstrumentTypeDDL,
  // CreateAllMachineBulkHeathCheck,
  // GetInventoryStatement,
  // SaveAuditLog,
  // VerifyOTP,
  // GetCostElementByCostCenterForExpense,
  // MillRulesApproval,
  // GetMillRuleWithHeaderAsync,
  // CoomonApprovalList,
  // GetItemRequestViewById,
  // CommonApproved,
  // BOMApprovalLanding,
  // BOMApproval,
  // GetPONOLcNoforLCSummeryDDL,
  // GetInfoFromPoLcDDLApprove,
  // ImportCostSheetReport,
  // GetShipmentById,
  // ApproveCommercialCoating,
  // GetLoanItemLanding,
  // ItemInventoryLoanTransaction,
  // GetBusinessPartnerbyIdDDL,
  // GetBusinessUnitByAccountDDL,
  // GetFundTransferApprovaListForCreatePagination,
  // CreateOrEditFundTransferRequest,
  // GetPendingAdjustments,
  GetAllVisitorRequest,
  AcceptOrRejectVisitorRequest,
  // CreateVisitorAppointment,
  // GetAllMyOutgoingRequest,
  // GetPendingAdjustmentRowViewByTransId,
  // AdjustmentApproval,
  // PartnerRegistrationApproval,
  // GetVehicleNearbyLocation,
  // ShippingLocationTracking,
  get_meeting_room_calender,
  // GetValidateExpenseAttachment,
  // DeleteExpenseRegisterRow,
  create_meeting_event,
  get_meeting_room_calender_modified,
  list_user_task_modified,
  create_user_task,
  // GetItemMasterCategoryDDL,
  // GetItemMasterSubCategoryDDL,
  // LighterVesselLocationTracking,
  // truck_api,
  truck_api_token,
  'https://akij.vftracker.com/location_api/api/execute',
  // GetServiceItemListByWhId,
  // GetAssetListForWorkOrder,
  // CreateWorkOrder,
  // GetCostCenterList,
  // GetMntWorkOrderList,
  // GetMaintenanceWorkOrder,
  // GetMaintenceTaskRowData,
  // EditWorkOrder,
  // CreateMntTask,
  // GetMaintenaceTaskItemList,
  // GetPartsList,
  // GetRuningStockAndQuantityList,
  // CreateMntItemTask,
  // CancelMntItemTask,
  // CreateItemRequestForAssetMaintenance,
  // GetProjectDDL,
  // GetEmployeeRegisterSummaryAllUnit,
  // GetFuelCostByEmployee,
  // GetCustomerAssessmentDocumentType,
  // CreateCustomerPreAssesment,
  // GetBillUpdateFuelCostByEmployee,
  // GetCustomerPreAssessmentLanding,
  // GetCustomerPreAssessmentValueByType,
  // GetCustomerPreAssessmentApprovalInfo,
  // CreateCustomerPreAssessmentApproval,
  // GetMaintenanceBreakdown,
  // CreateSalesForceAssessment,
  GetSalesForceEmployeeDDL,
  // GetSalesForcePreAssessmentLanding,
  // GetSalesForceAssessmentApprovalInfo,
  // CreateSalesForceAssessmentApproval,
  list_user_task,
  CreateVoiceRecord,
  GetVoiceRecord,
  // CreateSupplierAdvanceAfterPoApproved,
  // AppLoginLinkedin,
  chat,
  // GetDemandPlan,
  // SaveOrUpdateManpowerTaskPerform,
  // GetEmployeeWiseProfitCenterConfig,
  // GetCostElementByTransportDDL,
];

export { withoutEncryptionApi };
